### ISSUE TITLE
希望添加更加直观的白名单功能

### ISSUE THREAD

**Issue by sakuyamaij** [xdtianyu/CallerInfo#11]
今天接到DHL的电话021-20826666. 但是该号码被app注明为骚扰电话
由于同时使用了插件, 该电话就直接被挂断了.

目前只想到2种临时对策.
1.将该号码存入联系人后,app设置忽略联系人
2.暂时将插件关了

针对这种app"误伤", 建议加入白名单功能.

PS:还有个小小的建议,能否恢复强制中文的功能,手机一直是非中文的系统. app一直是英文状态.
不想装xposed修改语言...

**Comment by xdtianyu** [comment]
强制中文 的设置一直在啊，需要点击7次版本号打开隐藏功能。

**Comment by xdtianyu** [comment]
隐藏功能中，自定义数据源里有个忽略号码段也可以作为白名单来用。

**Comment by sakuyamaij** [comment]
谢谢,因为软件实在太方便平时很少折腾,忘记有隐藏功能了.再次感谢.

**Comment by fcying** [comment]
@xdtianyu 忽略号码段用起来不方便. 能不能 在长按历史记录的时候, 出一个 添加到忽略号码的功能?
