### ISSUE TITLE
锁屏，来电不显示悬浮窗

### ISSUE THREAD

**Issue by fenghuamu** [xdtianyu/CallerInfo#118]
*感谢您对【来电信息】应用的反馈*
*如果您正在提交一个 BUG，请按照模板填写信息。*
*如果您正在提交一个功能请求，请填写使用情景以便我们获取必要的信息*

#### 复现步骤:
1.锁屏待机
2.电话呼入，状态栏出现【来电信息】图标，但主屏无悬浮窗，看不到归属地信息。

**Comment by LovGate** [comment]
黑莓priv，同样的问题

**Comment by LovGate** [comment]
更新一下，在黑莓priv上还有个很奇特的bug，就是推开滑盖接听电话，浮窗会变成两倍大小，合上滑盖继续变大一倍，再滑开又变大一倍，直到占满整个屏幕。但是点击屏幕上的接听按钮则不会变大。当然这个问题并不影响使用。

**Comment by ZheminM** [comment]
MIUI10 安卓8.0 小米mix2
callerinfo 版本2.5.2
目前还是有这样的问题。
通知权限全部给到位，电源管理选择无限制并且后台锁定不被杀。
也会出现类似问题。
