### ISSUE TITLE
建议增加的功能

### ISSUE THREAD

**Issue by vobasf** [xdtianyu/CallerInfo#12]
1.白名单和黑名单
白名单不自动挂断
黑名单自动挂断

2.呼入超过N次以后，不自动挂断
可以选择针对黑名单有效或者无效

**Comment by Kellan123** [comment]
为什么没有自定义标记，比如标记公司名称之类的；还有建议可以更改自定义标记，现在有些数据错误，但根本无法更改

**Comment by xdtianyu** [comment]
已经在开发计划中了，请耐心等待～

Kellan123 <notifications@github.com>于2016年7月12日星期二 16:41写道：
