### ISSUE TITLE
可以增加正则表达式拦截吗？

### ISSUE THREAD

**Issue by miroku365** [xdtianyu/CallerInfo#122]
比如像nekosms那样，这样可以多拦截到一些还没标记的垃圾电话。

**Comment by xdtianyu** [comment]
> 可以自动挂断匹配的标记关键字(诈骗、广告等)、归属地、起始号码(400*)。归属地可逆向匹配，如 "!西安 !咸阳" 将挂断所有除 "西安" "咸阳" 的来电。起始号码关键字添加完整号码并以空格分隔可以实现 "黑名单" 的功能。

想要做成什么样子的呢？

**Comment by miroku365** [comment]
比如0???5*这样可以一次屏蔽不同区号下5开头的电话

**Comment by xdtianyu** [comment]
可以用起始号码拦截的方式 比如 400*

**Comment by HankAviator** [comment]
无区号来电通过匹配前缀的模式可能还是不方便，比如下面列表
```
95029267
97067664
95210373
95217110
95093147
98584318
98584318
95146089
95029248
95889915
97672959
97672959
97672959
97672959
97672959
97672959
97672959
97672959
98564602
95093147
90303265
99803003
95213455
```
也有95开头的，需要匹配位数才能避免误拦截
