### ISSUE TITLE
插件中添加号码到通话记录不管用

### ISSUE THREAD

**Issue by mailshuxin** [xdtianyu/CallerInfo#13]
不管是否开启“添加号码到通话记录”功能，都会在通话记录中添加信息，设置功能不能用

**Comment by xdtianyu** [comment]
感谢反馈，目前自动挂断的号码会被加入进去提醒用户，不知道你是不是说的这种情况？

mailshuxin <notifications@github.com>于2016年6月12日星期日 15:10写道：

**Comment by mailshuxin** [comment]
是的，之所以自动挂断就是因为太烦，可是总会在通话记录中添加拒接的电话

**Comment by xdtianyu** [comment]
感谢反馈，会尽快修改～

mailshuxin <notifications@github.com>于2016年6月12日星期日 15:15写道：

**Comment by mailshuxin** [comment]
可能我对这个设置没有理会清楚，我理解为这个功能就是开关是否在通话记录中是否添加拦截的电话信息

**Comment by xdtianyu** [comment]
在 [v2.1.4](https://github.com/xdtianyu/CallerInfo/releases/tag/v2.1.4) 增加了"添加响一声和自动挂断信息到通话记录" 设置，默认关闭，关闭状态不再添加响一声和自动挂断的提示。
