### ISSUE TITLE
忽略已存在联系人无效

### ISSUE THREAD

**Issue by hizjz** [xdtianyu/CallerInfo#130]
#### 复现步骤:
1.打开来电信息设置，显示与隐藏，开启“忽略已存在的联系人号码”
2.通讯录内的联系人打电话给我。

**Comment by xdtianyu** [comment]
Hi, 设置里 “忽略已存在的联系人号码” 下边有一个"显示联系人离线归属地"的选项，请检查下是不是打开了。
