### ISSUE TITLE
功能建议：增加95开头电话号码屏蔽设置功能

### ISSUE THREAD

**Issue by Erichinese** [xdtianyu/CallerInfo#137]
功能建议：增加95开头电话号码屏蔽设置功能
功能模块：插件功能设置-挂断号码关键字
问题描述：国内以95开头的号码多是营销电话，但若以95为关键字设置，理论上会屏蔽非95营销电话（没验证）。

谢谢您的插件！

**Comment by xdtianyu** [comment]
请再详细描述下期望的行为，最好举下号码例子。我不太明白问题描述里的逻辑关系，谢谢。

**Comment by magicwaltzlzy** [comment]
关键字设置95*即可，95在中间的号码不受影响

**Comment by igsony** [comment]
没错如果关键字设95*的话会把所有95开头的电话统统拒接，这样8位的95123456营销电话确实被拒绝了但同时5位的95588也会拒绝，而95588是工商银行客服啊
