### ISSUE TITLE
157号段怎么拦截

### ISSUE THREAD

**Issue by yezhengnong** [xdtianyu/CallerInfo#138]
*感谢您对【来电信息】应用的反馈*
*如果您正在提交一个 BUG，请按照模板填写信息。*
*如果您正在提交一个功能请求，请填写使用情景以便我们获取必要的信息*

#### 复现步骤:
1.
2.

**Comment by yezhengnong** [comment]
好用

**Comment by xdtianyu** [comment]
如果是 157 开头号段，可以在插件中使用 `157*` 拦截
