### ISSUE TITLE
移除通话记录权限

### ISSUE THREAD

**Issue by xdtianyu** [xdtianyu/CallerInfo#144]
由于 Google play 策略变更，需要移除通话记录权限

**Comment by nickzouli** [comment]
https://www.xda-developers.com/tasker-exemption-google-sms-call-log-restriction/
https://www.reddit.com/r/tasker/comments/acheqp/update_sms_and_call_permissions_success/

**Comment by xdtianyu** [comment]
已通过版本更新，向Google申述获取权限。

https://www.youtube.com/watch?v=ZmxXKdXD6qk

https://www.youtube.com/watch?v=QhwT4afuxiw

https://www.youtube.com/watch?v=tv469zx1JL8
