### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [xdtianyu/CallerInfo#147]
可以发布到 F-Droid 吗？

**Comment by xdtianyu** [comment]
发布到 fdroid 应该需要用它的证书签名，callerinfo 使用的自己的签名，所以应该不能发布到fdroid，如果有什么有用的信息，欢迎提供，谢谢。

**Comment by linsui** [comment]
请问 callerinfo 是在使用自己的签名时才可以工作吗？是否可以从源码构建？如果不能构建，或许可以和 Gallery 一样发布到 IzzySoft 的 repo 。

**Comment by xdtianyu** [comment]
@linsui 是的，同一个应用的签名是不能改变的，不然安装会报错。是从源码构建的

**Comment by linsui** [comment]
如果重新安装会出问题吗？另外现在 F-Droid 有一种可重现构建的方式，如果校验 F-Droid 构建的安装包和上游相同，会直接推送上游的安装包。
[Reproducible Builds](https://f-droid.org/docs/Reproducible_Builds/?title=Deterministic,_Reproducible_Builds)
[Are reproducible builds possible now?](https://forum.f-droid.org/t/are-reproducible-builds-possible-now/335)

**Comment by xdtianyu** [comment]
@linsui 这个 doc 我之前有看过，没有更细节的信息。当时咨询了下几乎是不可能实现的。我先自己摸索尝试下看看能不能实现。

**Comment by linsui** [comment]
或许可以先发布到 IzzySoft 的 repo？我会去提出请求，看看能不能接受

**Comment by xdtianyu** [comment]
@linsui OK, 如果你有时间的话欢迎帮忙提交到 IzzySoft

**Comment by linsui** [comment]
由于应用获取敏感信息，同时有多个追踪器，IzzySoft 拒绝了

https://gitlab.com/IzzyOnDroid/repo/issues/50#note_144280501

这些追踪器可以移除吗？或许你需要构建一个 Floss 版本才能发布到 F-Droid 。F-Droid 拒绝包含谷歌组件的应用。
期待好消息，谢谢 :smile:

**Comment by xdtianyu** [comment]
Google 的服务 Firebase 数据分析，以及 bugly 都是用来追踪程序停止运行错误日志的。移除这些库，可能需要自建数据分析服务了。覆盖完整自动化测试，版本稳定后，可以考虑移除这些第三方数据分析功能。

**Comment by ivysrono** [comment]
+1

**Comment by linsui** [comment]
应用似乎已经停止开发了
