### ISSUE TITLE
移除离线数据更新失败通知提醒

### ISSUE THREAD

**Issue by xdtianyu** [xdtianyu/CallerInfo#173]
From gmail:

大哥离线数据更新的确不错而且非常棒，但是让他静悄悄的后台更新就好了不要在状态栏通知提醒了可以吗。:sleepy:

**Comment by keepthinkingit** [comment]
> From gmail:
> 
> 大哥离线数据更新的确不错而且非常棒，但是让他静悄悄的后台更新就好了不要在状态栏通知提醒了可以吗。😪

如果是 aosp 类系统 , 7.0 以上直接按着消息不动 , 一秒后就能管理通知状态 . 或者进设置-通知 进行管理 .
miui 8.0 global 直接进设置改通知显示方式就行了 . 

这种问题你不应该自己查说明书看自己的手机设置么 ?

**Comment by xdtianyu** [comment]
@keepthinkingit 网络失败通知太过频繁，会在下个版本优化下
