### ISSUE TITLE
增加事后标记的功能

### ISSUE THREAD

**Issue by nick-tru** [xdtianyu/CallerInfo#18]
@xdtianyu 现在未标记过的来电在挂断后，有弹出窗口进行标记的功能，但这个窗口仍停留1秒就关闭了，根本来不及选择和标记（也许是我的手机问题，HTC ONE M8，Android 6.0，HTC Sence 7.0）。
能否增加事后标记的功能，或者是延长标记窗口的停留时间？

**Comment by xdtianyu** [comment]
感谢反馈，这个标记的窗口不会自动消失的，只有标记后才会消失。被关闭会不会是触摸了对话框外部引起的？

nick-tru <notifications@github.com>于2016年7月19日星期二 16:58写道：

**Comment by nick-tru** [comment]
我确定没有触摸对话框外部，都是在选择标记类型时，眼睁睁看着对话框就此消失，所谓“手慢无”的感觉！
以前用过触宝来电显示，就可以事后再进行标记，所以能否建议增加事后标记的功能。谢谢！

**Comment by xdtianyu** [comment]
主界面已经添加了标记号码的入口，通过长按卡片可以弹出底部表单，如果新版本还有出现窗口自动消失的问题，请重新提一个 issue，谢谢～
