### ISSUE TITLE
打开项目时as报错ERROR: For input string: ""

### ISSUE THREAD

**Issue by IMPLannister** [xdtianyu/CallerInfo#183]
*感谢您对【来电信息】应用的反馈*
*如果您正在提交一个 BUG，请按照模板填写信息。*
*如果您正在提交一个功能请求，请填写使用情景以便我们获取必要的信息*

#### 复现步骤:
1.
2.

**Comment by xdtianyu** [comment]
https://github.com/xdtianyu/CallerInfo/blob/master/DEVELOPMENT-CN.md

**Comment by IMPLannister** [comment]
感谢解答
