### ISSUE TITLE
去电时自动挂断什么意思？

### ISSUE THREAD

**Issue by zhengyiZ** [xdtianyu/CallerInfo#19]
作者你好，app中有一个“禁用去电时自动挂断”的开关，这是什么意思？是说往外打电话时自动挂断吗?

另：在app中的其他中，有作者的邮箱，如果是用于接收反馈的，建议加入文字链接，这样方便直接跳转到编辑邮件界面。

**Comment by xdtianyu** [comment]
“禁用去电时自动挂断” 就是说去电时不会自动挂断

张正义 <notifications@github.com>于2016年7月22日星期五 20:20写道：
