### ISSUE TITLE
骚扰电话响铃几声后才自动挂断，请问能更快速吗？

### ISSUE THREAD

**Issue by yebr** [xdtianyu/CallerInfo#20]
如果能够在响铃前挂断，耳朵会清静很多，请问从技术上（免root）能否实现响铃前挂断？
如果不能，就只有自定义铃声然后前几秒插入静音了。

**Comment by xdtianyu** [comment]
离线数据中没有号码信息会联网查询，这个联网的过程就比较尴尬了。应用在联网查询这里还可以继续优化，而且离线号码资源也越來越多。联网较慢时应用可以在查询到号码前将系统静音之类的来临时禁用响铃，查到后恢复之前状态，这也是一个方法。
