### ISSUE TITLE
在国外很多垃圾电话不能正常识别

### ISSUE THREAD

**Issue by mailshuxin** [xdtianyu/CallerInfo#27]
在国外，有时国内的电话显示为＋862139001234这样的格式，有时显示为862139001234这样的格式,当显示为86开头时，就能正常识别了，希望能修正
还有400也是的，400基本上全是垃圾电话，在国外显示为＋400开头，结果全部不能识别

**Comment by mailshuxin** [comment]
上面的描述有错误，显示为86开头时，不能识别，显示为＋86开头，能识别一些，但基本上很多都不能识别，很怪

**Comment by xdtianyu** [comment]
感谢反馈~

**Comment by xdtianyu** [comment]
请耐心等待更新，在 v2.1.0 及之后新版版检验下~
