### ISSUE TITLE
来电是 + 开头的查询没解决？ 版本  2.1.0

### ISSUE THREAD

**Issue by yorks** [xdtianyu/CallerInfo#29]
比如: 
+0190852213
直接查询 0190852213 是可以查到的。

**Comment by xdtianyu** [comment]
目前没有对这个 `+019***` 这样的号码做本地处理，只是对 `+86, +400` 这样的号码做了 [处理](https://github.com/xdtianyu/CallerInfo/blob/master/app/src/main/java/org/xdty/callerinfo/data/CallerRepository.java#L69)。但是我在主界面搜索可以查询到网络数据的啊

**Comment by yorks** [comment]
的确走网络是可以查到， 看来是今天的离线数据还没有？

**Comment by xdtianyu** [comment]
感谢反馈～这个号码离线数据应该是没有的，含有+应该没有做处理，后续会优化

yorks <notifications@github.com>于2016年8月16日星期二 18:38写道：

**Comment by xdtianyu** [comment]
2.1.3 版本已修复这个问题，出现 `+10086` `+019085xxxx` 这样在正常号码前多 "+" 的应该可以正确查到本地数据了，欢迎验证~
