### ISSUE TITLE
请求支持：设置忽略四位数集团短号

### ISSUE THREAD

**Issue by septs** [xdtianyu/CallerInfo#3]

**Comment by septs** [comment]
例如：1111, 1011, 1001, 2222 这样的号码识别出来结果是错误的 通常集团短号都是有备注或者知道对方身份 因此并不需要

**Comment by xdtianyu** [comment]
@septs 感谢反馈，是需要白名单功能吗？还是要在悬浮窗的时候标记？

**Comment by septs** [comment]
四位数号码不需要 标记

**Comment by xdtianyu** [comment]
已添加忽略号码设置，可以在`隐藏设置`(点击七次版本出现)-`自定义数据源`-`忽略号码段` 中 添加 `****` 来忽略所有的四位号码。
