### ISSUE TITLE
移动的一机双号副号无法识别

### ISSUE THREAD

**Issue by Zeact** [xdtianyu/CallerInfo#30]
和 #9  类似的问题，但是浙江移动用的是1259023开头作为副号的识别，希望也能修正下

**Comment by xdtianyu** [comment]
这种 `1259023` 的号码和 `12583` 一样会在之后加入一位序号吗？ `12583` 似乎会加入序号变成 `125821, 125832  ...` 这样。

**Comment by xdtianyu** [comment]
在 v2.1.2 版本上已经增加了 1259023 的判断，请检查～

**Comment by Zeact** [comment]
1259023后面直接就跟号码了，不会加序号。目测已经可以识别，没想到作者那么快就修正并且在play上更新了，赞~
