### ISSUE TITLE
[bug]1183348 起始的号码查询失败

### ISSUE THREAD

**Issue by ipivi** [xdtianyu/CallerInfo#31]
最新版，1183348 起始的号码查询失败；它类似1259023是一个一卡双号的前缀；
显示号码为 “1183348+手机号”，在查询归属地时需先过滤，然后直接查询后面的号码；
建议：加上对1183348的过滤，或者将其做成一个功能设置项，由用于自己设置，先过滤哪些前缀，然后查询，

**Comment by xdtianyu** [comment]
感谢反馈，会尽快添加

ipivi <notifications@github.com>于2016年8月22日星期一 14:20写道：

**Comment by xdtianyu** [comment]
[v2.1.5](https://github.com/xdtianyu/CallerInfo/releases/tag/v2.1.5) 已添加
