### ISSUE TITLE
如何去掉误标记，无主动上传

### ISSUE THREAD

**Issue by drboook** [xdtianyu/CallerInfo#32]
如何去除误标记

**Comment by xdtianyu** [comment]
可以长按卡片在自定义选择自定义，输入空内容并点击键盘确认键

**Comment by drboook** [comment]
啥卡片？

**Comment by xdtianyu** [comment]
在主界面，找到被标记的号码卡片，长按会弹出带有编辑功能的底部栏。这个功能后续会优化加入更显眼的去除标记功能，另外下一个新版本 v2.1.5 这种自定义留空的方式会实效，标记时请尽量谨慎。

**Comment by drboook** [comment]
长按会出现底部栏但无法修改

**Comment by xdtianyu** [comment]
在被自己标记的号码上长按会出现可编辑的底部栏，条件是被自己标记或者已接听且没有找到标记数据的号码。

**Comment by lzwhuhu** [comment]
您好，我遇到了基本同样的问题，我之前不小心给一个号码添加了自定义标签，后来我想取消自定义标签，但是不会，于是瞎点，点到了“诈骗”，然后再想取消就取消不了了，这个号码之前给我打过电话，求助…

**Comment by xdtianyu** [comment]
@lzwhuhu 可以再次自定义标签，删除输入框文字变成空，再按回车。感谢反馈，后续会优化这个。

**Comment by lzwhuhu** [comment]
好像标记后它自动上传了，而不是

**Comment by lzwhuhu** [comment]
抱歉手机故障没打完，可是我没法重新自定义标签，那个编辑按钮不显示，只有每次清除缓存后有不到一秒的时间，号码显示未标记，只有这时可以编辑标签

**Comment by xdtianyu** [comment]
@lzwhuhu 感谢反馈，这个问题会在近期优化

**Comment by lzwhuhu** [comment]
明白了，非常感谢

**Comment by lzwhuhu** [comment]
您好，就是上次误标记之后…在您更新前我刷了个机…于是现在这个误标记还在…但是没法编辑了，请问还有解决办法吗
