### ISSUE TITLE
建议: 支持多重数据源匹配

### ISSUE THREAD

**Issue by youfou** [xdtianyu/CallerInfo#35]
目前选择数据源的方式为单选，也就是只在其中一个数据源中进行查找匹配。
但存在部分号码在A数据源中已被标记，而B数据源中尚未标记的情况。
而对于部分被骚扰情况比较严重的用户，则希望采取更更严格的过滤方式：只要在其中一个数据源中发现被标记，即认为这个号码为骚扰/广告电话。

因此建议：
选择数据源时，改用复选框的方式，支持多重匹配。
具体逻辑是，轮询所有用户**已选择的数据源**，返回第一个已知类型的结果。
后期可再考虑多重匹配的源排序的实现。

**Comment by xdtianyu** [comment]
这个数据源的选择是优先的意思，如果在一个数据源里没有查找到数据会继续在其他数据源中查询的。

youfou <notifications@github.com>于2016年8月30日星期二 17:56写道：

**Comment by youfou** [comment]
原来如此，太好了。
可以将“数据源”字样，修改为“优先采用数据源”之类的，这样避免更多类似我这种误解。

**Comment by xdtianyu** [comment]
感谢反馈~
