### ISSUE TITLE
希望通讯录中存在的号码即使被标记也不被拦截

### ISSUE THREAD

**Issue by cosimahan** [xdtianyu/CallerInfo#38]
作者好, 感谢您的软件, 我希望通讯录中存在的号码即使被标记也不被拦截, 可否加个选项?

**Comment by xdtianyu** [comment]
请在设置中打开 显示与隐藏-忽略联系人号码 开关。打开这个设置后应该不会再查询联系人的号码信息了。

Cosima <notifications@github.com>于2016年9月11日周日 15:59写道：
