### ISSUE TITLE
Google Play无法更新最新版本1.3.6

### ISSUE THREAD

**Issue by xyalan** [xdtianyu/CallerInfo#4]
设备：Nexus5X
系统：6.0.1
版本号：MMB29Q
APP是从Google Play下载，最近Google Play提示有1.3.6更新，其他所有APP都正常更新，唯独`来电信息`一直出错，提示错误代码497。
Google搜索找到解决方法发是停用Google Play，清除数据然后卸载更新再重启设备，略显麻烦。对Android不熟悉，不知道是否是这边上传到Google Play有问题。如果这边没问题，便按照Google上找到的答案试试。

**Comment by xdtianyu** [comment]
这个应该是因为网络的问题

**Comment by xyalan** [comment]
换了代理现在尝试已经可以。
