### ISSUE TITLE
现在支持的有多少数据源？

### ISSUE THREAD

**Issue by LvHengshan** [xdtianyu/CallerInfo#47]
仔细看了下代码，应该只有聚合数据源在使用吧？
百度、搜狗、leancloud的似乎没用起来吧？
谢谢

**Comment by xdtianyu** [comment]
除了百度的 API 已经不支持了以外，聚合数据、搜狗都有使用啊

[PhoneNumber.java#L101](https://github.com/xdtianyu/PhoneNumber/blob/master/phone-number/src/main/java/org/xdty/phone/number/PhoneNumber.java#L101)

[PhoneNumber.java#L220](https://github.com/xdtianyu/PhoneNumber/blob/master/phone-number/src/main/java/org/xdty/phone/number/PhoneNumber.java#L220)

**Comment by LvHengshan** [comment]
看到了，谢谢
