### ISSUE TITLE
可以为你的项目捐赠吗？

### ISSUE THREAD

**Issue by kcschan** [xdtianyu/CallerInfo#5]
因为你的软件受益良多(功能限定于单纯的来电信息的，只有CallerInfo这一个应用)，希望表达谢意。

**Comment by xdtianyu** [comment]
感谢反馈，目前还没有接受捐赠的计划，考虑后期添加一个捐赠的入口，我再汇总起来捐赠给乌干达儿童等需要的人，之类的
