### ISSUE TITLE
是否有号码段屏蔽功能？

### ISSUE THREAD

**Issue by meijialun** [xdtianyu/CallerInfo#53]
例如我想屏蔽本地所有固话，或者400开头的一切号码，是否有这样的功能？

**Comment by xdtianyu** [comment]
`插件-号码关键字` 输入 `400` 即可。

插件功能(安装插件后出现)

1. 自动挂断。可以自动挂断匹配的标记关键字(诈骗、广告等)、归属地、起始号码(400*)。归属地可逆向匹配，如 "!西安 !咸阳" 将挂断所有除 "西安" "咸阳" 的来电。起始号码关键字添加完整号码并以空格分隔可以实现 "黑名单" 的功能。

**Comment by meijialun** [comment]
感谢反馈，请问如何安装插件，在首页介绍中没有找到？
