### ISSUE TITLE
请问如何更新本地号码库？

### ISSUE THREAD

**Issue by yibin001** [xdtianyu/CallerInfo#55]
我本地号码库还是1个月以前的，不能手工同步更新么？

**Comment by xdtianyu** [comment]
稍等我晚上更新下，8点后应该就可以收到新数据了。因为现在离线数据越來越大，每天会走很多流量，每个月费用不少，所以我把之前的自动更新关掉了。

为了解决数据量过大的问题，需要开发一个离线增量更新的功能，春节那会在重构来实现这个，还没有搞完。 https://github.com/xdtianyu/PhoneNumber

**Comment by yibin001** [comment]
谢谢。
