### ISSUE TITLE
突然悬浮框上没有任何骚扰提示

### ISSUE THREAD

**Issue by yibin001** [xdtianyu/CallerInfo#58]
这两天发现来电时，悬浮框没有任何提示，但是在“来电信息”app的主界面里能看到来电的标记，这是怎么回事？
p.s.现在去电，悬浮框也是空白，什么都不显示。

**Comment by yibin001** [comment]
我知道是什么原因了，我启用了"文字颜色"，可能文子的颜色与背景色一致，导致我认为没有提示。

**Comment by xdtianyu** [comment]
感谢反馈!
