### ISSUE TITLE
国外接电话无法正确对接电话号码数据

### ISSUE THREAD

**Issue by fieldyyueng** [xdtianyu/CallerInfo#6]
以国外接听广州固话为例，如果来电号码是020-88888888，在callerinfo里显示的号码是2088888888，因话电话号码变了，所以会出现“no data”的结果。
请修正一下这个错误，谢谢

**Comment by xdtianyu** [comment]
感谢反馈

fieldyyueng <notifications@github.com>于2016年3月28日星期一 01:55写道：

**Comment by 264768502** [comment]
在国外接电话还会在开头附上加号
+4001600127 会查询失败
4001600127 会查询成功

**Comment by 264768502** [comment]
另外+862131010426这样的查询不到
但是去掉+86
然后补齐3位的区号就查的到
02131010426

**Comment by xdtianyu** [comment]
@264768502 感谢反馈~

**Comment by xdtianyu** [comment]
新版本上应该解决这个问题了～
