### ISSUE TITLE
离线数据库已经两个月没有更新了

### ISSUE THREAD

**Issue by yibin001** [xdtianyu/CallerInfo#60]
版本210，更新时间 2017-03-11 10:13:41。

**Comment by GoGoogle** [comment]
离线数据库是该更新一下了
但这数据一般人搞不到啊

**Comment by xdtianyu** [comment]
@GoGoogle 好的我晚上手动更新一下，Sorry 好久没更新了，期望我有时间完成数据后台和差分更新功能。：（（（

**Comment by GoGoogle** [comment]
@xdtianyu 辛苦了！
这数据库不知道从哪儿搞来，本身可以自定义数据库就很好，但数据库不知从何来.

感谢！

**Comment by GoGoogle** [comment]
@xdtianyu 更新过了？我怎么接收不到更新。。。

**Comment by xdtianyu** [comment]
@GoGoogle 没呢，今天晚上了更新，这几天一直没能获取到离线数据 https://forum.leancloud.cn/t/topic/15383

**Comment by kkzhang** [comment]
现在离线数据版本212，7月份更新的。这样的更新频率不行啊。得有个自动更新机制。

**Comment by sausager** [comment]
这里也是无法获取离线数据更新，目前用着7月份的212版本，试过各种梯子都未能更新成功，看来不是我的网络问题吧？

**Comment by xdtianyu** [comment]
这几天会出一个版本，更换离线数据服务器。每天会有些异常流量需要过滤下，不然每月离线数据开销也不少😂

**Comment by kkzhang** [comment]
可以考虑离线导入数据包

2017-12-12 21:25 GMT+08:00 tianyu <notifications@github.com>:

**Comment by renwairen** [comment]
离线数据一直更新失败
