### ISSUE TITLE
使用钛备份恢复应用后应用不会自动申请联系人权限

### ISSUE THREAD

**Issue by xdujiang** [xdtianyu/CallerInfo#67]
用钛备份恢复应用数据后打开应用，应用不会自动申请联系人权限，导致“不标记联系人号码”功能失效，需要手动授权或者手动关闭再开启此功能。
关闭“不标记联系人号码”时系统才会弹出联系人权限申请的对话框。

**Comment by xdtianyu** [comment]
感谢反馈~
