### ISSUE TITLE
CallerInfo-v2.0.0-beta1 设置 NPE

### ISSUE THREAD

**Issue by gythialy** [xdtianyu/CallerInfo#7]
Google Play Store 更新的版本，点设置直接退出应用，看日志是 NPE，详细信息见截图

![421156800](https://cloud.githubusercontent.com/assets/773400/15454325/2c8bfc62-2068-11e6-8b99-bb52cd99cd80.jpg)

**Comment by xdtianyu** [comment]
感谢反馈～是处理插件设置时出现的异常，已经修改了～

**Comment by gythialy** [comment]
这个修改 Play Store什么时候会更新？我以为数据库变了，把 app 的设置全部清空了，现在设置不了了 😂😂😂

Send from my Nexus 6P.

**Comment by xdtianyu** [comment]
这两天就会更新了，可以临时安装插件应用解决这个问题😵

**Comment by gythialy** [comment]
嗯，临时安装个插件，可以使用了，多谢
