### ISSUE TITLE
升级2.0后无法实现自动挂断功能

### ISSUE THREAD

**Issue by sakuyamaij** [xdtianyu/CallerInfo#8]
Android6.0.1
Nexus5
主程序和插件为google play商店的最新版本

当来电已被tag为骚扰等关键字时，依然无法自动挂断
1.X.X版本时一切正常

**Comment by xdtianyu** [comment]
感谢反馈～这个问题已经确认，查询到本地归属地数据后再查到号码信息将不能挂断，已经在 v2.0.4 版本修复。
