### ISSUE TITLE
2.3.0release版本在lineageOs14.1上无法解析包安装

### ISSUE THREAD

**Issue by sailfish-jjk** [xdtianyu/CallerInfo#83]
2.3.0release版本在lineageOs14.1上无法解析包安装，一加1，安卓7.1.2

**Comment by xdtianyu** [comment]
感谢反馈，请试下运行命令 `adb shell install xxx.apk ` 看看出现的错误是什么？

**Comment by sailfish-jjk** [comment]
可以正常安装play store上的版本
