### ISSUE TITLE
一加3T OOS 安卓8.0系统上，通知栏始终显示，2个应用正在后台运行含来电信息，来电信息插件

### ISSUE THREAD

**Issue by ezrick** [xdtianyu/CallerInfo#95]
该通知为 android系统发出，并非软件通知，不能通过关闭软件通知来消除

**Comment by xdtianyu** [comment]
请问是哪一个系统版本？我用的氧os open beta 22，没有这种通知

**Comment by ezrick** [comment]
freedom 3.3 ce  + magisk + xposed,,估计是bata 20左右，， 可能是版本问题，我之前刷第三方的8.1没这个问题

**Comment by gythialy** [comment]
freedom 3.3 也有这个问题，而且如果强行把 callerinfo 关闭了，后面就再也不显示了，就算手动把 callerinfo 启起来也不行

**Comment by ezrick** [comment]
我已经刷到了官方oos bata 22,    通知的问题没了， 但是程序似乎不会自启动，启动手机后需要手动开一下

**Comment by ezrick** [comment]
氧os open beta 22 现在有2个问题，1是 app不会自启动，每次开机需要手工开一次，2是，那个通知，一开始没有，在有过一次来电后就有了
